[package]
name = "tiny-crawler1"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
thiserror = "2.0.16"
scraper = "0.24.0"
futures = "0.3.31"
url = "2.5.7"